config/routes.rb
Rails.application.routes.draw do

  post 'attachments/ng_upload'
  delete 'attachments/ng_delete/:id' => 'attachments#ng_delete'

  get 'stylesheets/theme', as: 'theme_css'

  root 'home#index'

  get '/blog' => 'blog#index'
  get '/blog/:id' => 'blog#show', as: 'post'
  get '/blog/tag/:tag' => 'blog#tag', as: 'tag'
  get '/blog/posts/category/:category' => 'blog#by_category', as: 'by_category'
  get '/blog/posts/month/:month' => 'blog#by_month', as: 'by_month'

  namespace :admin do
    get '/', to: redirect('/admin/posts'), as: :root
    resources :posts
    resources :categories, except: [:show]
    resources :assets
    resources :users
    resources :admins, controller: 'users', only: [:create, :update, :new, :edit], type: 'admin'
    resources :customers, controller: 'users', only: [:create, :update, :new, :edit], type: 'customer'
    resources :configurations, except: [:index]
    resources :preferences
    resources :space_types, except: [:show]
  end

  namespace :customer do
    get '/' => "home#index", as: :root
    match '/', to: "home#update", via: [:put, :patch], as: :update
    match '/update_password', to: "home#update_password", via: [:put, :patch], as: :update_password
    resources :project_requests
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :file, {
    url: "/system/:class/:id/:hash.:extension",
    hash_secret: "string_for_obfuscation_from_hell"
  }

  validates_attachment_presence :file
  do_not_validate_attachment_file_type :file
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < Admin::AdminController
  before_action :set_admin_asset, only: [:show, :edit, :update, :destroy]
  before_action :set_request_host

  # GET /admin/assets
  # GET /admin/assets.json
  def index
    @assets = Asset.all
  end

  # GET /admin/assets/1
  # GET /admin/assets/1.json
  def show
  end

  # GET /admin/assets/new
  def new
    @asset = Asset.new
  end

  # GET /admin/assets/1/edit
  def edit
  end

  # POST /admin/assets
  # POST /admin/assets.json
  def create
    @asset = Asset.new(admin_asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to admin_assets_url, notice: t('controllers.assets.create.success') }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/assets/1
  # PATCH/PUT /admin/assets/1.json
  def update
    respond_to do |format|
      if @asset.update(admin_asset_params)
        format.html { redirect_to admin_assets_url, notice: t('controllers.assets.udpate.success') }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/assets/1
  # DELETE /admin/assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to admin_assets_url, notice: t('controllers.assets.destroy.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_asset_params
      params[:asset].permit!
    end

    def set_request_host
      @hostname = 'http://' + (request.host || "www.dicoreinterirores.com.br") + (request.port != 80 ? ":#{request.port}" : '')
    end
end

app/helpers/admin/assets_helper.rb
module Admin::AssetsHelper
end

app/views/admin/assets/_form.html.erb
<%= simple_form_for([:admin, @asset]) do |f| %>
  <%= f.error_notification %>

  <div class="box-body">
    <div class="row">
      <div class='col-md-8'>
        <%= f.input :description %>
      </div>
    </div>

    <div class="row">
      <div class='col-md-8'>
        <%= f.input :file %>
      </div>
    </div>
  </div>

  <div class="box-footer">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/assets/edit.html.erb
<% content_for :page_header, 'Arquivos' %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Editando Arquivo</h3>
  </div>
  <div class="box-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/assets/index.html.erb
<% content_for :page_header, 'Arquivos' %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('views.admin.menu.assets') %></h3>
    <div class="box-tools pull-right">
      <%= link_to t('views.admin.new_asset'), new_admin_asset_path, class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

  <div class="box-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= t('generic.description') %></th>
          <th><%= t('generic.file') %></th>
          <th><%= t('generic.created_at') %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @assets.each do |asset| %>
        <tr>
          <td><%= asset.description %></td>
          <td>
            <div class="input-group" style="max-width: 300px">
              <input class="form-control input-sm" id="asset_url<%= asset.id %>" value="<%= @hostname + asset.file.url %>"/>
              <div class="input-group-btn">
                <button class="btn btn-default btn-sm clipboard-btn" data-clipboard-target="#asset_url<%= asset.id %>" type="button">
                  <i alt="Copy to clipboard" class="fa fa-clipboard"></i>
                </button>
                <%= link_to asset.file.url, class: 'btn btn-default btn-sm' do %>
                <i alt="Copy to clipboard" class="fa fa-download"></i>
                <% end %>
              </div>
            </div>
          </td>
          <td><%= asset.created_at %></td>
          <td>
            <div class="btn-group btn-group-xs" role="group">
              <%= link_to edit_admin_asset_path(asset), class: 'btn btn-warning' do %>
              <i class="fa fa-pencil"></i><% end %>
              <%= link_to admin_asset_path(asset), method: :delete, data: { confirm: t('generic.are_you_sure') }, class: 'btn btn-danger' do %>
              <i class="fa fa-trash"></i><% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/assets/new.html.erb
<% content_for :page_header, 'Arquivos' %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Novo Arquivo</h3>
  </div>

  <div class="box-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/assets/show.html.erb
<div class="box-body">
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </div>

  <%= link_to t('generic.edit'), edit_admin_asset_path(@asset), class: 'btn btn-primary' %>
  <%= link_to t('generic.back'), admin_assets_path, class: 'btn btn-danger' %>
</div>