config/routes.rb
Rails.application.routes.draw do

  post 'attachments/ng_upload'
  delete 'attachments/ng_delete/:id' => 'attachments#ng_delete'

  get 'stylesheets/theme', as: 'theme_css'

  root 'home#index'

  get '/blog' => 'blog#index'
  get '/blog/:id' => 'blog#show', as: 'post'
  get '/blog/tag/:tag' => 'blog#tag', as: 'tag'
  get '/blog/posts/category/:category' => 'blog#by_category', as: 'by_category'
  get '/blog/posts/month/:month' => 'blog#by_month', as: 'by_month'

  namespace :admin do
    get '/', to: redirect('/admin/posts'), as: :root
    resources :posts
    resources :categories, except: [:show]
    resources :assets
    resources :users
    resources :admins, controller: 'users', only: [:create, :update, :new, :edit], type: 'admin'
    resources :customers, controller: 'users', only: [:create, :update, :new, :edit], type: 'customer'
    resources :configurations, except: [:index]
    resources :preferences
    resources :space_types, except: [:show]
  end

  namespace :customer do
    get '/' => "home#index", as: :root
    match '/', to: "home#update", via: [:put, :patch], as: :update
    match '/update_password', to: "home#update_password", via: [:put, :patch], as: :update_password
    resources :project_requests
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

end

app/views/shared/404.html.erb
<section class="content-404">
  <div class="content-404-style container">
      <i class="fa fa-cog icon-404"></i>
      <h1 class="title-404">404</h1>
      <p><%= t('generic.404_error') %></p>
      <div class="entry-404-meta">
          <%= link_to t('generic.go_home'), root_path %>
      </div>
  </div>
</section>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//dicoreonline.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<!-- Begin Footer -->
<footer class="tz-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4 footerattr footer-logo">
        <aside class="widget_contact_info widget" id="contact_info-2">
          <%= link_to image_tag('logo-draw.svg', class: 'footer-logo-1'), root_path %>
          <%= link_to image_tag('logo-text.svg', class: 'footer-logo-2'), root_path %>
        </aside>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 footerattr copyright-area">
        <aside class="widget_widget_logo widget" id="widget_logo-2">
          <p> <%= t('generic.copyright') %> <%= Time.new.year %> <%= t('generic.app_name').upcase %>. </p>
          <p> <%= t('generic.copyright_msg') %> </p>
        </aside>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 footerattr contact-area">
        <aside class="widget_tz_social widget" id="tz_social-2">
          <p><%= t('generic.get_in_touch') %></p>
          <p> <%= "#{t('generic.get_in_touch_name')}" %> </p>
          <p> <%= "#{t('generic.get_in_touch_email')}" %> </p>

          <!-- <h3 class="module-title title-widget">
            <span> <%= t('generic.social_networks') %> </span>
          </h3>
          <div class="tz_social">
            <a class="fa fa-facebook" href="https://www.facebook.com/DIcore-1502685986693256/?ref=ts&fref=ts" target="_blank"></a>
            <a class="fa fa-instagram" href="https://www.instagram.com/dicoreinteriores/" target="_blank"></a>
            <a class="fa fa-google-plus" href="#"></a>
            <a class="fa fa-twitter" href="#"></a>
            <a class="fa fa-youtube" href="#"></a>
          </div> -->
        </aside>
      </div>
    </div>
    <!--end class row-->
  </div>
  <!--end class container-->
</footer>
<!-- End Footer -->

app/views/shared/_head.html.erb
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="<%= t('generic.app_name') %>" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title><%= t('generic.app_name') %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel='stylesheet' href='<%= theme_css_path %>' type='text/css' media='all' />
    <%= csrf_meta_tags %>

    <link rel='stylesheet' id='Varela-css' href='http://fonts.googleapis.com/css?family=Varela' type='text/css' media='all' />
    <link rel='stylesheet' id='Rouge-css' href='http://fonts.googleapis.com/css?family=Rouge+Script' type='text/css' media='all' />
</head>

app/views/shared/_header.html.erb
<header class="tz-header tz-header-page">
  <div class="container">
    <button 
      class="btn-navbar tz_icon_menu pull-right" 
      data-target=".nav-collapse" 
      type="button"
    >
      <i class="fa fa-bars"></i>
    </button>

    <h3 class="tzlogo pull-left">
      <a class="pull-left tz_logo" href="/" title="Dicore Online">
        <%= image_tag 'logo.png', class: 'logo_lager', height: '120' %>
      </a>
    </h3>
    <%= render 'shared/header_menu' %>
  </div>
</header>

app/views/shared/_header_main.html.erb
<header class="tz-header tz-header1">
  <div class="wrapbox">
    <div class="container">
      <button class="btn-navbar tz_icon_menu pull-right" data-target=".nav-collapse" type="button">
        <i class="fa fa-bars"></i>
      </button>
      <h3 class="tzlogo pull-left">
        <a class="pull-left tz_logo" href="/" title="Dicore Online">
          <%= image_tag 'logo.png', class: 'logo_lager', style: 'height: 110px; margin-top: -10px;' %>
        </a>
      </h3>
      <%= render partial: 'shared/header_menu', locals: {nav_class: 'tznav-menu'} %>
    </div>
  </div>
</header>

app/views/shared/_header_menu.html.erb
<nav class="pull-left <%= local_assigns[:nav_class] %>">
  <ul class="tz-menu nav-collapse themeple_megemenu" id="menu-primary">
    <li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-has-children" id="menu-item-102">
      <%= link_to t('views.menu.home'), root_path %>
    </li>

    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children" id="menu-item-183">
      <%= link_to t('views.menu.blog.label'), blog_path, target: '_blank' %>
    </li>

    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children" id="menu-item-183">
      <%= link_to t('views.menu.admin_panel'), admin_root_path if current_user.present? and current_user.type == 'Admin' %>
      <%= link_to t('views.menu.customer_panel'), customer_root_path if current_user.present? and current_user.type == 'Customer' %>
    </li>

    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children" id="menu-item-183">
      <%= link_to t('views.app.auth.sign_in'), new_user_session_path if !current_user.present? %>
      <%= link_to t('views.app.auth.sign_out'), destroy_user_session_path, method: 'delete' if current_user.present? %>
    </li>
  </ul>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, message| %>
  <% if message.is_a?(String) && message.present? %>
    <% if key == 'notice' %>
      <div id="message" class="alert alert-info" role="alert">        
    <% elsif key == 'alert' %>
      <div id="message" class="alert alert-danger" role="alert">
    <% end %>
      <%= simple_format(message) %>
      </div>
  <% end %>
<% end %>