config/routes.rb
Rails.application.routes.draw do

  post 'attachments/ng_upload'
  delete 'attachments/ng_delete/:id' => 'attachments#ng_delete'

  get 'stylesheets/theme', as: 'theme_css'

  root 'home#index'

  get '/blog' => 'blog#index'
  get '/blog/:id' => 'blog#show', as: 'post'
  get '/blog/tag/:tag' => 'blog#tag', as: 'tag'
  get '/blog/posts/category/:category' => 'blog#by_category', as: 'by_category'
  get '/blog/posts/month/:month' => 'blog#by_month', as: 'by_month'

  namespace :admin do
    get '/', to: redirect('/admin/posts'), as: :root
    resources :posts
    resources :categories, except: [:show]
    resources :assets
    resources :users
    resources :admins, controller: 'users', only: [:create, :update, :new, :edit], type: 'admin'
    resources :customers, controller: 'users', only: [:create, :update, :new, :edit], type: 'customer'
    resources :configurations, except: [:index]
    resources :preferences
    resources :space_types, except: [:show]
  end

  namespace :customer do
    get '/' => "home#index", as: :root
    match '/', to: "home#update", via: [:put, :patch], as: :update
    match '/update_password', to: "home#update_password", via: [:put, :patch], as: :update_password
    resources :project_requests
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  layout "blog"
  impressionist :actions => [:show]

  before_action :load_archives, :load_categories, :load_populars, only: [:index, :by_category, :by_month, :show, :tag]

  def index
    @posts = PostQuery.new.search.published_ordered.page(params.fetch(:page, 1))
  end

  def show
    begin
      @post = Post.find_by_id_and_draft!(params[:id], false)
      impressionist(@post)
    rescue ActiveRecord::RecordNotFound
      render_not_found
    end
  end

  def tag
    @posts = Post.tagged_with(params[:tag]).where(draft: false).order(created_at: :desc).page(params.fetch(:page, 1))
    render 'index'
  end

  def by_category
    @posts = Post.where(category: params[:category]).page(params.fetch(:page, 1))
    render 'index'
  end

  def by_month
    @posts = PostQuery.new.search.by_month(params[:month].to_date).page(params.fetch(:page, 1))
    render 'index'
  end

  private

  def load_archives
    @archives = PostQuery.new.search.archives
  end

  def load_categories
    @categories = Category.all
  end

  def load_populars
    impressions = Impression.select(:impressionable_id).where(impressionable_type: 'Post').group(:impressionable_id).order('count(impressionable_id) DESC').distinct.limit(5)
    @populars = Post.where(:id => impressions)
  end
end

app/views/blog/_footer.html.erb
<!-- Begin Footer -->
<footer class="tz-footer blog-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4 footerattr">
        <aside class="widget_contact_info widget" id="contact_info-2">
          <%= link_to image_tag('logo-draw.svg', class: 'footer-logo-1'), root_path %>
          <%= link_to image_tag('logo-text.svg', class: 'footer-logo-2'), root_path %>
        </aside>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 footerattr copyright-area">
        <aside class="widget_widget_logo widget" id="widget_logo-2">
          <p> <%= t('generic.copyright') %> <%= Time.new.year %> <%= t('generic.app_name').upcase %>. </p>
          <p> <%= t('generic.copyright_msg') %> </p>
        </aside>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 footerattr contact-area">
        <aside class="widget_tz_social widget" id="tz_social-2">
          <p><%= t('generic.get_in_touch') %></p>
          <p> <%= "#{t('generic.get_in_touch_name')}" %> </p>
          <p> <%= "#{t('generic.get_in_touch_email')}" %> </p>

          <!-- <h3 class="module-title title-widget">
            <span> <%= t('generic.social_networks') %> </span>
          </h3>
          <div class="tz_social">
            <a class="fa fa-facebook" href="https://www.facebook.com/DIcore-1502685986693256/?ref=ts&fref=ts" target="_blank"></a>
            <a class="fa fa-instagram" href="https://www.instagram.com/dicoreinteriores/" target="_blank"></a>
            <a class="fa fa-google-plus" href="#"></a>
            <a class="fa fa-twitter" href="#"></a>
            <a class="fa fa-youtube" href="#"></a>
          </div> -->
        </aside>
      </div>
    </div>
    <!--end class row-->
  </div>
  <!--end class container-->
</footer>
<!-- End Footer -->

app/views/blog/_head.html.erb
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="<%= t('generic.app_name') %>" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <title><%= t('generic.app_name') %></title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel='stylesheet' href='<%= theme_css_path %>' type='text/css' media='all' />
    <%= csrf_meta_tags %>

    <script type="text/javascript">
        var themeprefix = 'plazart';
        var imgpath = 'images/';
    </script>

    <!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="vc-ie8.css" media="screen">
    <![endif]-->
</head>

app/views/blog/_header.html.erb
<header class="tz-header tz-header-page blog-header">
    <div class="container">
        <button data-target=".nav-collapse" class="btn-navbar tz_icon_menu" type="button">
            <i class="fa fa-bars"></i>
        </button>
        <h3 class="tzlogo pull-left">
            <%= link_to root_path, title: t('generic.app_name') do %>
                <%= image_tag 'logo-draw.svg', id: 'logo-img' %>
                <%= image_tag 'logo-text.svg', id: 'logo-text' %>
            <% end %>
        </h3>

        <%= render 'blog/header_menu' %>
    </div>
</header>

app/views/blog/_header_menu.html.erb
<nav class="pull-right menu-left-margin <%= local_assigns[:nav_class] %>">
  <ul class="tz-menu nav-collapse themeple_megemenu" id="menu-primary">
    <li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-has-children" id="menu-item-102">
      <%= link_to t('views.menu.home'), blog_path %>
    </li>

    <% Category.header_categories.each do |category| %>
      <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children" id="menu-item-183">
        <%= link_to category.name, by_category_path(category.id) %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/blog/_right_section.html.erb
<!-- <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block;max-height:250px;margin: 0 0 10px 0"
     data-ad-client="ca-pub-4116031825041905"
     data-ad-slot="2080524670"
     data-ad-format="rectangle,vertical">
</ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script> -->


<script async src="//"></script>
<!-- retangulo médio -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-4116031825041905"
     data-ad-slot="2029615877"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<aside id="recent-posts-2" class="widget_categories widget">
  <h3 class="module-title title-widget right-section-header">
    <%= t("views.blog.populars") %>
  </h3>

  <ul>
    <% @populars.each do |post| %>
      <li class="cat-item cat-item-14 right-section-item">
          <%= link_to post.title, post %>
      </li>
    <% end %>
  </ul>
</aside>

<aside id="categories-2" class="widget_categories widget">
  <h3 class="module-title title-widget right-section-header">
    <%= t("views.blog.categories") %>
  </h3>

  <ul>
    <% @categories.each do |categ| %>
      <li class="cat-item cat-item-14 right-section-item">
        <%= link_to categ.name, by_category_path(categ.id) %>
      </li>
    <% end %>
  </ul>
</aside>

<aside id="archives-2" class="widget_archive widget">
  <h3 class="module-title title-widget right-section-header">
    <%= t("views.blog.archives") %>
  </h3>

  <ul>
    <% @archives.each do |k,v| %>
      <li class="cat-item cat-item-14 right-section-item">
        <%= link_to l(k.to_date, format: :month_year), by_month_path(k.to_date) %>
      </li>
    <% end %>
  </ul>
</aside>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Teste -->
<ins class="adsbygoogle"
     style="display:block;max-height:250px;margin: 10px 0 10px 0"
     data-ad-client="ca-pub-4116031825041905"
     data-ad-slot="3557257876"
     data-ad-format="rectangle,vertical"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<aside id="categories-2" class="widget_categories widget right-section-social-widget">
  <h3 class="module-title title-widget right-section-social-header">
    FACEBOOK
  </h3>

  <ul>
    <li class="cat-item cat-item-14 right-section-item">
      <div class="fb-page" data-href="https://www.facebook.com/DIcore-1502685986693256/?ref=ts&amp;fref=ts" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
    </li>
  </ul>
</aside>

<aside id="categories-2" class="widget_categories widget right-section-social-widget">
  <h3 class="module-title title-widget right-section-social-header">
    INSTAGRAM
  </h3>

  <ul>
    <li class="cat-item cat-item-14 right-section-item">
      <!-- SnapWidget -->
      <script src="http://snapwidget.com/js/snapwidget.js"></script>
      <iframe src="http://snapwidget.com/in/?u=ZGljb3JlaW50ZXJpb3Jlc3xpbnw4MHwyfDN8fHllc3w1fG5vbmV8b25TdGFydHx5ZXN8eWVz&ve=190116" title="Instagram Widget" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%;"></iframe>
    </li>
  </ul>
</aside>

<div id="fb-root"></div>
<% content_for :scripts do %>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
<% end %>

app/views/blog/index.html.erb
<div class="home-post">
  <div class="tzblog-columns">
    <div class="container">
      <div class="row tzshow_sidebar">
        <div class="col-md-8">
          <% @posts.each_with_index do |post, index| %>
            <article
              id="post-<%= post.id %>"
              class="post-<%= post.id %> post type-post status-publish format-standard has-post-thumbnail hentry category-blog tag-love tag-songs blog-post"
            >
              <% unless post.main_image.nil? %>
                <div class="tzblog-img tzblog-format">
                  <a href="<%= post_path(post.id) %>">
                    <%= image_tag post.main_image.url(:cropped), class: 'attachment-post-thumbnail wp-post-image img-responsive' %>
                  </a>
                </div>
              <% end %>

              <h2 class="tzblog-title"><%= link_to post.title, post_path(post.id) %></h2>

              <div class="blog_meta">
                <span class="tzblog_date">
                  <%= l post.created_at %>
                </span>

                <span class="tztags_link">
                  <% post.tags.each do |tag| %>
                    <%= link_to tag.name, tag_path(tag.name) %>
                  <% end %>
                </span>
              </div>

              <div class="tzthe_content">
                <p><%= post.introduction %></p>
                <%= link_to t('views.blog.see_more'), post_path(post.id), class: 'more-link' %>
              </div>

              <% if index == 0 %>
                <div class="tzthe_content text-center">
                  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                  <!-- Teste -->
                  <ins class="adsbygoogle"
                       style="display:block"
                       data-ad-client="ca-pub-4116031825041905"
                       data-ad-slot="5033991073"
                       data-ad-format="rectangle,horizontal"></ins>
                  <script>
                  (adsbygoogle = window.adsbygoogle || []).push({});
                  </script>
                </div>
              <% end %>
            </article>
          <% end %>

          <div class="tzpagenavi-blog">
            <%= paginate @posts %>
          </div>
        </div>

        <div class="col-md-3 tzsidebar-event">
          <%= render 'right_section' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog/show.html.erb
<div class="tzdefault_title">
  <div class="container">
    <h1>Blog - <%= @post.title %></h1>
  </div>
</div>
<div class="single_post">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <% unless @post.main_image.nil? %>
          <div class="tzblog-img">
            <%= image_tag @post.main_image.url, class: 'img-responsive' %>
          </div>
        <% end %>
        <h2 class="single-title"><%= @post.introduction %></h2>
        <span class="single-meta">
          <%= l @post.created_at %>
        </span>
        <div class="single-content blog-content">
          <%= markdown(@post.body) %>
        </div>
        <div class="single-tags">
          <div class="meta-tags pull-left">
            Tags:
            <% @post.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag.name) %>
            <% end %>
          </div>
          <div class="single-share pull-right">
            <span>Share it:</span>
            <a class="tz_social" href="javascript: void(0)" id="fb-share" onclick="window.open('http://www.facebook.com/sharer.php?s=100&amp;p[title]=<%= @post.title %>&amp;p[url]=<%= request.original_url %>','sharer','toolbar=0,status=0,width=580,height=325');">
              <i class="fa fa-facebook"></i>
            </a>

            <a class="tz_social" href="javascript: void(0)" id="tw-share" onclick="window.open('http://twitter.com/share?text=<%= @post.title %>&amp;url=<%= request.original_url %>','sharer','toolbar=0,status=0,width=580,height=325');">
              <i class="fa fa-twitter"></i>
            </a>

            <a class="tz_social" href="javascript: void(0)" id="p-share" onclick="window.open('http://pinterest.com/pin/create/button/?url=<%= request.original_url %>;description=<%= @post.title %>','sharer','toolbar=0,status=0,width=580,height=325');">
              <i class="fa fa-pinterest"></i>
            </a>
          </div>
        </div>
        <div class="single-author">
          <%= image_tag @post.author.avatar(:smaller), class: 'avatar avatar-100 photo' %>
          <span class="author-ds">
            <a class="single-author-name"><%= @post.author.full_name %></a>
            <a class="single-author-name"><%= @post.author.email %></a>
          </span>
        </div>
        <div class="tzcomments-area">
          <div class="comments-area" id="comments">
            <%= render 'shared/disqus' %>
          </div>
        </div>
      </div>
      <div class="col-md-3 tzsidebar-event">
        <%= render 'right_section' %>
      </div>
    </div>
  </div>
</div>