config/routes.rb
Rails.application.routes.draw do

  post 'attachments/ng_upload'
  delete 'attachments/ng_delete/:id' => 'attachments#ng_delete'

  get 'stylesheets/theme', as: 'theme_css'

  root 'home#index'

  get '/blog' => 'blog#index'
  get '/blog/:id' => 'blog#show', as: 'post'
  get '/blog/tag/:tag' => 'blog#tag', as: 'tag'
  get '/blog/posts/category/:category' => 'blog#by_category', as: 'by_category'
  get '/blog/posts/month/:month' => 'blog#by_month', as: 'by_month'

  namespace :admin do
    get '/', to: redirect('/admin/posts'), as: :root
    resources :posts
    resources :categories, except: [:show]
    resources :assets
    resources :users
    resources :admins, controller: 'users', only: [:create, :update, :new, :edit], type: 'admin'
    resources :customers, controller: 'users', only: [:create, :update, :new, :edit], type: 'customer'
    resources :configurations, except: [:index]
    resources :preferences
    resources :space_types, except: [:show]
  end

  namespace :customer do
    get '/' => "home#index", as: :root
    match '/', to: "home#update", via: [:put, :patch], as: :update
    match '/update_password', to: "home#update_password", via: [:put, :patch], as: :update_password
    resources :project_requests
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable
         #, :confirmable

   has_attached_file :avatar, styles: {thumb: '160x160#', smaller: '100x100#'},
   default_url: "/default_assets/default-user-avatar-:style.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

   validates_presence_of :name
   validates_presence_of :surname
   validates_presence_of :cpf
   validates_presence_of :phone1

   def full_name
     "#{name} #{surname}"
   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    if params[:type] == 'admin'
      @user = Admin.new
    elsif params[:type] == 'customer'
      @user = Customer.new
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if params[:type] == 'admin'
      @user = Admin.new(user_params)
    elsif params[:type] == 'customer'
      @user = Customer.new(user_params)
    else
      @user = User.new(user_params)
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: t('controllers.users.update.success') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: t('controllers.users.destroy.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[params[:type]].permit!
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  layout "login"

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<!-- form start -->
<%= simple_form_for([:admin, @user]) do |f| %>
<%= f.error_notification %>
<%= f.input :type, as: :hidden %>

<div class="box-body">
  <div class="row">
    <div class="col-md-6">
      <%= f.input :name %>
    </div>
    <div class="col-md-6">
      <%= f.input :surname %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :email %>
    </div>
    <div class="col-md-6">
      <%= f.input :password, as: :password %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :cpf %>
    </div>
    <div class="col-md-4">
      <%= f.input :phone1 %>
    </div>
    <div class="col-md-4">
      <%= f.input :phone2 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= f.input :street %>
    </div>
    <div class="col-md-4">
      <%= f.input :street_number %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.input :street_complement %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :city %>
    </div>
    <div class="col-md-4">
      <%= f.input :state %>
    </div>
    <div class="col-md-4">
      <%= f.input :zip_code %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.input :avatar %>
    </div>
  </div>

<div class="box-footer">
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to t('generic.cancel'), admin_users_path, class: 'btn btn-danger' %>
</div>

<% end %>

app/views/admin/users/edit.html.erb
<% content_for :page_header, t('views.admin.users.edit') %>
<div class="box box-primary">
  <div class="box-header with-border">
    
  </div>
  <div class="box-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for :page_header, 'Usuários do Sistema' %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"> <%= t('views.admin.users.all') %>  </h3>
    <div class="box-tools pull-right">
      <div class="btn-group btn-group-sm">
        <%= link_to t('views.admin.new_admin'), new_admin_admin_path, class: 'btn btn-primary' %>
        <%= link_to t('views.admin.new_customer'), new_admin_customer_path, class: 'btn btn-info' %>
      </div>
    </div>
  </div>

  <div class="box-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.user.name') %></th>
          <th class="hidden-sm hidden-xs"><%= t('activerecord.attributes.user.surname') %></th>
          <th><%= t('activerecord.attributes.user.email') %></th>
          <th><%= t('activerecord.attributes.user.type') %></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td class="hidden-sm hidden-xs"><%= user.surname %></td>
          <td><%= user.email %></td>
          <td><%= user.type %></td>
          <td>
            <div class="btn-group btn-group-xs" role="group">
              <%= link_to admin_user_path(user), class: 'btn btn-primary' do %>
              <i class="fa fa-eye"></i><% end %>
              <%= link_to edit_admin_user_path(user), class: 'btn btn-warning' do %>
              <i class="fa fa-pencil"></i><% end %>
              <%= link_to admin_user_path(user), method: :delete, data: { confirm: t('generic.are_you_sure') }, class: 'btn btn-danger' do %>
              <i class="fa fa-trash"></i><% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :page_header, 'Usuários do Sistema' %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Novo Usuário</h3>
  </div>
  <div class="box-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% content_for :page_header, t('views.admin.users.title') %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Exibindo Usuário</h3>
    <div class="box-tools pull-right">
      <div class="btn-group btn-group-sm" role="group">
        <%= link_to t('views.admin.users.edit'), edit_admin_user_path(@user), class: 'btn btn-primary' %>
        <%= link_to t('views.admin.users.show'), admin_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

  <div class="box-body">

    <div class="row">
      <div class="col-md-2">
        <%= image_tag @user.avatar.url(:thumb), class: 'img-responsive img-circle' %>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-2">
            <b>Nome</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.name %></p>
          </div>
          <div class="col-md-2">
            <b>Sobrenome</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.surname %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <b>Email</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.email %></p>
          </div>
          <div class="col-md-2">
            <b>CPF</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.cpf %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <b>Telefone 1</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.phone1 %></p>
          </div>
          <div class="col-md-2">
            <b>Telefone 2</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.phone2 %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <b>Rua</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.street %></p>
          </div>
          <div class="col-md-2">
            <b>Número</b>
          </div>
          <div class="col-md-3">
            <p><%= @user.street_number %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-1">
            <b>CEP</b>
          </div>
          <div class="col-md-2">
            <p><%= @user.zip_code %></p>
          </div>
          <div class="col-md-1">
            <b>Cidade</b>
          </div>
          <div class="col-md-2">
            <p><%= @user.city %></p>
          </div>
          <div class="col-md-1">
            <b>Estado</b>
          </div>
          <div class="col-md-2">
            <p><%= @user.state %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>